# Generated by Django 3.2.4 on 2021-08-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问卷标题')),
                ('content', models.TextField(verbose_name='问卷备注')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('first_shared_date', models.DateTimeField(verbose_name='初次发布时间')),
                ('last_shared_date', models.DateTimeField(verbose_name='最新发布时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('status', models.CharField(choices=[('deleted', '处于回收站中'), ('shared', '已发布'), ('closed', '未发布')], default='closed', max_length=50, verbose_name='问卷状态')),
                ('type', models.CharField(choices=[('normal', '普通问卷'), ('vote', '投票问卷'), ('exam', '考试问卷'), ('signup', '报名问卷')], default='normal', max_length=50, verbose_name='问卷类型')),
                ('is_locked', models.BooleanField(default=False, verbose_name='访问是否需要密码')),
                ('password', models.CharField(default='', max_length=255, verbose_name='访问密码')),
                ('is_required_login', models.BooleanField(default=False, verbose_name='填写是否需要登录')),
                ('is_only_answer_once', models.BooleanField(default=False, verbose_name='是否只允许回答一次')),
                ('order_type', models.CharField(choices=[('order', '按照题号排序显示'), ('disorder', '乱序显示')], default='order', max_length=50, verbose_name='问卷题目显示方式')),
                ('is_show_result', models.BooleanField(default=False, verbose_name='是否为填写者显示填写的统计结果')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目备注')),
                ('type', models.CharField(choices=[('single-choice', '单选题'), ('multiple-choice', '多选题'), ('completion', '填空题'), ('scoring', '评分题')], max_length=50, verbose_name='问题类型')),
                ('order_type', models.CharField(choices=[('order', '按照选项排序号正序显示'), ('disorder', '乱序显示')], default='order', max_length=50, verbose_name='题目选项的显示方式')),
                ('ordering', models.PositiveIntegerField(verbose_name='题目序号')),
                ('is_must_answer', models.BooleanField(default=False, verbose_name='是否必答')),
                ('is_limit_answer', models.BooleanField(default=False, verbose_name='是否限制该题答题人数')),
                ('limit_answer_number', models.IntegerField(default=0, verbose_name='该题限制的答题人数')),
                ('is_scoring', models.BooleanField(default=False, verbose_name='是否评分')),
                ('question_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='题目分数')),
                ('answer', models.TextField(blank=True, verbose_name='参考答案')),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire', verbose_name='问卷ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='选项标题')),
                ('content', models.TextField(verbose_name='选项备注')),
                ('ordering', models.PositiveIntegerField(verbose_name='选项序号')),
                ('is_limit_answer', models.BooleanField(default=False, verbose_name='是否限制该选项选择人数')),
                ('limit_answer_number', models.IntegerField(default=0, verbose_name='该选项限制的选择人数')),
                ('is_answer_choice', models.BooleanField(default=False, verbose_name='该选项是否为答案')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='该选项/填空分数')),
                ('answer', models.CharField(max_length=255, verbose_name='参考答案')),
                ('validator_regex', models.CharField(max_length=255, verbose_name='以正则表达形式式存储的字段检查正则式')),
                ('is_must_answer', models.BooleanField(default=False, verbose_name='是否必答')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question', verbose_name='题目ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(verbose_name='答卷序号')),
                ('content', models.TextField(blank=True, null=True, verbose_name='选项填空内容')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.option', verbose_name='选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question', verbose_name='题目')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire', verbose_name='问卷')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='答卷人')),
            ],
        ),
    ]
