# Generated by Django 3.2.4 on 2021-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='参考答案'),
        ),
        migrations.AlterField(
            model_name='option',
            name='validator_regex',
            field=models.CharField(blank=True, max_length=255, verbose_name='以正则表达形式式存储的字段检查正则式'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='first_shared_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初次发布时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='last_shared_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最新发布时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='访问密码'),
        ),
    ]
